use_frameworks!
platform :ios, '8.0'

target 'GlossExample' do

pod 'Gloss', :git => 'https://github.com/hkellaway/Gloss.git', :branch => 'feature/custom_operator'

end

target 'GlossExampleTests' do

end

