use_frameworks!
platform :ios, '8.0'

target 'GlossExample' do

pod 'Gloss', :git => 'https://github.com/hkellaway/Gloss.git', :branch => 'fix/forced_decoding_cleanup'

end

target 'GlossExampleTests' do

end

